name: ms-datastore
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - jupyter
  - xcube >=1.8.1
  - xcube-cci >=0.11.2
  - xcube-cds >=0.9.3
  - xcube-clms >=0.2.2
  #- xcube-stac
  - xcube-zenodo >=0.1.1