name: xcube-multistore
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - dask
  - fsspec
  - numpy
  - panel
  - pyproj
  - tabulate
  - xarray
  - xcube >=1.13.1
  - xcube-resampling >=0.3.0
  - yaml
  # Development Dependencies - Tools
  - black
  - isort
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings
  - mkdocstrings-python
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib