name: xcube-multistore
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - xcube >=1.8.1
  - xcube-cci >=0.11.2
  - xcube-cds >=0.9.3
  - xcube-clms >=0.2.2
  - xcube-stac >=0.1.0
  - xcube-zenodo >=0.1.1
  # Development Dependencies - Tools
  - black
  - isort
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib