datasets:
  # define dataset Changes in Global Terrestrial Live Biomass
  # over the 21st Century by Xu et al.
  - identifier: biomass_xu
    store: zenodo
    grid_mapping: gm_scs4
    data_id: "4161694/test10a_cd_ab_pred_corr_2000_2019_v2.tif"
    open_params:
      tile_size: [1800, 1800]
    format_id: netcdf
    custom_processing:
      module_path: "modify_dataset"
      function_name: "biomass_xu_merge_years"
  # define dataset for ESA CCI biomass
  - identifier: esa_cci_biomass
    store: esa_cci
    grid_mapping: gm_scs4
    data_id: "esacci.BIOMASS.yr.L4.AGB.multi-sensor.multi-platform.MERGED.5-0.10000m"
    format_id: netcdf

data_stores:
  # file data store for writing final cubes to local file system
  - identifier: storage
    store_id: file
    store_params:
      root: data
  # cci data store for CCI biomass
  - identifier: esa_cci
    store_id: cciodp
  # zenodo data store for canopy height and biomass map by Xu et al.
  - identifier: zenodo
    store_id: zenodo

grid_mappings:
  - identifier: gm_scs4
    bbox: [-180, -90, 180, 90]
    spatial_res: 0.1
    crs: EPSG:4326

general:
  visualize: False