datasets:
- identifier: AU-Dry_sen2
  store: stac-pc
  data_id: sentinel-2-l2a
  open_params:
    time_range: &id001
    - '2020-01-01'
    - '2020-03-30'
    point:
    - 132.3706
    - -15.2588
    bbox_width: 4000
    spatial_res: 10
    asset_names:
    - B01
    - B02
    - B03
    - B04
    - B05
    - B06
    - B07
    - B08
    - B8A
    - B09
    - B11
    - B12
    - SCL
- identifier: AU-Dry_era5
  store: cds
  data_id: reanalysis-era5-single-levels-timeseries
  open_params:
    variable_names:
    - 2m_temperature
    - 2m_dewpoint_temperature
    time_range: *id001
    location:
    - 132.3706
    - -15.2588
- identifier: AU-Dry_ccibiomass
  store: esa_cci
  grid_mapping: AU-Dry_sen2
  data_id: esacci.BIOMASS.yr.L4.AGB.multi-sensor.multi-platform.MERGED.5-0.100m
  open_params:
    time_range: *id001
- identifier: AU-How_sen2
  store: stac-pc
  data_id: sentinel-2-l2a
  open_params:
    time_range: *id001
    point:
    - 131.1523
    - -12.4943
    bbox_width: 4000
    spatial_res: 10
    asset_names:
    - B01
    - B02
    - B03
    - B04
    - B05
    - B06
    - B07
    - B08
    - B8A
    - B09
    - B11
    - B12
    - SCL
- identifier: AU-How_era5
  store: cds
  data_id: reanalysis-era5-single-levels-timeseries
  open_params:
    variable_names:
    - 2m_temperature
    - 2m_dewpoint_temperature
    time_range: *id001
    location:
    - 131.1523
    - -12.4943
- identifier: AU-How_ccibiomass
  store: esa_cci
  grid_mapping: AU-How_sen2
  data_id: esacci.BIOMASS.yr.L4.AGB.multi-sensor.multi-platform.MERGED.5-0.100m
  open_params:
    time_range: *id001
data_stores:
- identifier: storage
  store_id: file
  store_params:
    root: data
- identifier: esa_cci
  store_id: cciodp
- identifier: stac-pc
  store_id: stac-pc-ardc
- identifier: cds
  store_id: cds
  store_params:
    endpoint_url: https://cds.climate.copernicus.eu/api
    cds_api_key: CDS_API_key
    normalize_names: true
