name: Unittest xcube-multistore

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube-multistore
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pytest --cov=xcube_multistore --cov-report=xml
